# Variable substitution
# https://docs.docker.com/compose/compose-file/compose-file-v3/#variable-substitution
# 環境変数は local/Makefile で設定されています。
version: "3.7"
name: "sk_goa_chat_containers_localtest"
services:
  mysql:
    platform: linux/amd64
    image: mysql:8.0.35
    container_name: localtest_mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${APP_MYSQL_DATABASE_NAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "${APP_MYSQL_PORT}:3306"
    networks:
      - network1

  firebase-emulators:
    build:
      context: ../firebase-emulators
      dockerfile: Dockerfile
    ports:
      - "${APP_FIREBASE_AUTH_PORT}:9099"
    command: firebase emulators:start
    networks:
      - network1

networks:
  network1:
